# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # -------------------------------------------------
  # Base Box
  # -------------------------------------------------
  # ARM64 Ubuntu box compatible with Apple Silicon
  config.vm.box = "bento/ubuntu-22.04"

  # -------------------------------------------------
  # VM Identity
  # -------------------------------------------------
  config.vm.hostname = "main-server"

  # -------------------------------------------------
  # Network Configuration
  # -------------------------------------------------

  # Private network for VM-to-VM communication
  config.vm.network "private_network", ip: "192.168.56.10"

  # Optional port forwarding
  # Jenkins
  config.vm.network "forwarded_port",
    guest: 8080,
    host: 8080,
    auto_correct: true

  # -------------------------------------------------
  # Synced Folder
  # -------------------------------------------------
  # Disable default synced folder for better performance
  #

  # Optional custom synced folder
  # Uncomment if needed later
  #
  config.vm.synced_folder "../../", "/workspace", create: true
  config.vm.synced_folder "../../persistent-data/jenkins", "/persistent-data/jenkins", create: true

  # -------------------------------------------------
  # VMware Provider Configuration
  # -------------------------------------------------
  config.vm.provider "vmware_desktop" do |vmware|

    vmware.vmx["memsize"]  = "8192"
    vmware.vmx["numvcpus"] = "4"

    vmware.gui = false

  end

  # -------------------------------------------------
  # Disk Configuration
  # -------------------------------------------------
  # NOTE:
  # VMware disks are usually managed automatically.
  # Additional disk resizing can be handled later
  # if required.

  # -------------------------------------------------
  # SSH Configuration
  # -------------------------------------------------
  config.ssh.insert_key = false

  # -------------------------------------------------
  # Provisioning
  # -------------------------------------------------
  # Initial bootstrap structure
  config.vm.provision "shell",
  path: "../shared/scripts/bootstrap/main-server-bootstrap.sh", privileged: true

end