Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04-arm64"

  config.vm.hostname = "devops-main"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "vmware_desktop" do |v|
    v.vmx["memsize"] = "8192"
    v.vmx["numvcpus"] = "4"
  end

  # Provisioning
  config.vm.provision "shell", path: "scripts/common.sh"
  config.vm.provision "shell", path: "scripts/docker.sh"

end